# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHome():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_home(self):
    # Test name: home
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://reality-evolution.com/")
    # 2 | setWindowSize | 974x1032 |  | 
    self.driver.set_window_size(974, 1032)
    # 3 | click | css=.navbar-toggler-icon |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    # 4 | click | linkText=INICIO |  | 
    self.driver.find_element(By.LINK_TEXT, "INICIO").click()
  
